### ISSUE TITLE
On IDLE event throws exception

### ISSUE THREAD

**Issue by IngoMeyer441** [AyatanaIndicators/ayatana-webmail#25]
Sorry for bothering you again... I noticed mail notifications stop working after a few minutes, so I checked the logs and got this:

```
Exception in thread Thread-4 (idle):
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/application.py", line 878, in onIdle
    typ, msg_data = oConnection.oImap.uid('FETCH', m, '(X-GM-THRID BODY.PEEK[HEADER.FIELDS (DATE SUBJECT FROM MESSAGE-ID)])')
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1211, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1674, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1421, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))
ayatanawebmail.imaplib2.IMAP4.error: UID command error: BAD [b'expected fetch-att instead of "X-GM-THRID BO"']. Data: b'HPJA26 UID FETCH 8196 (X-GM-THRID BODY.PEEK[HEADER.FIELDS (DATE SUBJECT FROM MESSAGE-ID)])\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/idler.py", line 67, in idle
    self.fnCallback(self.oConnection, False)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/application.py", line 889, in onIdle
    typ, msg_data = oConnection.oImap.uid('FETCH', m, '(BODY.PEEK[HEADER.FIELDS (DATE SUBJECT FROM MESSAGE-ID)])')
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1211, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1674, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1327, in _command
    self._check_bye()
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/imaplib2.py", line 1274, in _check_bye
    raise self.abort(bye[-1].decode('ASCII', 'replace'))
ayatanawebmail.imaplib2.IMAP4.abort: too many errors
```

Maybe my mail provider (GMX) uses a IMAP server implementation which behaves a bit differently from the standard?

**Comment by ghost** [comment]
No problem, bug reports make software better. I will create a GMX account and test it.

**Comment by ghost** [comment]
@IngoMeyer441 

Could you please test the latest git version? Thanks.

```
# If ayatana-webmail is running, kill it first. Then:

git clone https://github.com/AyatanaIndicators/ayatana-webmail.git
cd ayatana-webmail
python setup.py build
sudo python setup.py install --root=/ --optimize=1
cd ..
sudo rm -fr ayatana-webmail

# Start it and leave it running in the terminal
ayatana-webmail
```

**Comment by IngoMeyer441** [comment]
Thanks for the quick fix! I had to fix a small syntax error (double colon):
```
Traceback (most recent call last):
  File "/usr/bin/ayatana-webmail", line 22, in <module>
    from ayatanawebmail.application import AyatanaWebmail
  File "/usr/lib/python3.10/site-packages/ayatanawebmail/application.py", line 873
    if any(s in oConnection.strHost for s in ['gmail', 'google'])::
```
but after this, it seems to work fine! I will test the new version in the next days and report if any problems occur.

**Comment by ghost** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/bin/ayatana-webmail", line 22, in <module>
>     from ayatanawebmail.application import AyatanaWebmail
>   File "/usr/lib/python3.10/site-packages/ayatanawebmail/application.py", line 873
>     if any(s in oConnection.strHost for s in ['gmail', 'google'])::
> ```
Oooops...! Sorry, fixed.

**Comment by IngoMeyer441** [comment]
Ah, now I understand that `X-GM-THRID` is a GMail extension to the IMAP protocol: https://developers.google.com/gmail/imap/imap-extensions#access_to_the_gmail_thread_id_x-gm-thrid

But that also means, that message thread support will only work on GMail accounts, correct?

**Comment by ghost** [comment]
> Ah, now I understand that `X-GM-THRID` is a GMail extension to the IMAP protocol: https://developers.google.com/gmail/imap/imap-extensions#access_to_the_gmail_thread_id_x-gm-thrid
> 
> But that also means, that message thread support will only work on GMail accounts, correct?

Yes. It's a Google thread extension. IMAP servers should simply ignore any X-properties which they do not support (or return a non-fatal result). GMX is apparently different - it goes into shock when it sees it.

**Comment by IngoMeyer441** [comment]
After testing the fix for a week, I can tell that it works without any further issues (for my setup). Thanks again for your time! I think, this issue can now be closed.
